let IDH = {
    idh2010:[
        {
            name:'Aguascalientes',
            abb:'AGU',
            idh:0.88  
        },
        {
            name:'Baja California',
            abb:'BCN',
            idh:0.877
        },
        {
            name: 'Baja California Sur',
            abb:'BCS',
            idh:0.879
        },
        {
            name:'Campeche',
            abb:'CAM',
            idh:0.821
        },
        {
            name: 'Ciudad de Mexico',
            abb: 'CMX',
            idh:0.954
        },
        {
            name:'Coahuila',
            abb: 'COA',
            idh:0.896
        },
        {
            name:'Colima',
            abb:'COL',
            idh:0.846
        },
        {
            name:'Chiapas',
            abb:'CHI',
            idh:0.724
        },
        {
            name:'Chihuahua',
            abb:'CHH',
            idh:0.864
        },
        {
            name:'Durango',
            abb:'DUR',
            idh:0.864
        },
        {
            name:'Estado de Mexico',
            abb:'EMX',
            idh:0.843
        },
        {
            name:'Guanajuato',
            abb:'GUA',
            idh:0.812
        },
        {
            name:'Guerrero',
            abb:'GRO',
            idh:0.752
        },
        {
            name:'Hidalgo',
            abb:'HID',
            idh:0.798
        },
        {
            name:'Jalisco',
            abb:'JAL',
            idh:0.854
        },
        {
            name:'Michoacan',
            abb:'MIC',
            idh:0.786
        },
        {
            name: 'Morelos',
            abb: 'MOR',
            idh:0.852
        },
        {
            name:'Nayarit',
            abb:'NAY',
            idh:0.793
        },
        {
            name:'Nuevo Leon',
            abb:'NVL',
            idh:0.922
        },
        {
            name:'Oaxaca',
            abb:'OAX',
            idh:0.733
        },
        {
            name:'Puebla',
            abb:'PUE',
            idh:0.809
        },
        {
            name:'Queretaro',
            abb:'QRO',
            idh:0.871
        },
        {
            name:'Quintana Roo',
            abb:'QNR',
            idh:0.889
        },
        {
            name:'San Luis Potosi',
            abb:'SLP',
            idh:0.828
        },
        {
            name:'Sinaloa',
            abb:'SIN',
            idh:0.821
        },
        {
            name:'Sonora',
            abb:'SON',
            idh:0.873
        },
        {
            name:'Tabasco',
            abb:'TAB',
            idh:0.795
        },
        {
            name:'Tamaulipas',
            abb:'TAM',
            idh:0.864
        },
        {
            name:'Tlaxcala',
            abb:'TLX',
            idh:0.790
        },
        {
            name:'Veracruz',
            abb:'VER',
            idh:0.780
        },
        {
            name:'Yucatan',
            abb:'YUC',
            idh:0.822
        },
        {
            name:'Zacatecas',
            abb:'ZAC',
            idh:0.801
        }
    ]
    ,
    idh2005:[
        {
            name:'Aguascalientes',
            abb:'AGU',
            idh:0.861
        },
        {
            name:'Baja California',
            abb:'BCN',
            idh:0.865
        },
        {
            name: 'Baja California Sur',
            abb:'BCS',
            idh:0.873
        },
        {
            name:'Campeche',
            abb:'CAM',
            idh:0.804
        },
        {
            name: 'Ciudad de Mexico',
            abb: 'CMX',
            idh:0.938
        },
        {
            name:'Coahuila',
            abb: 'COA',
            idh:0.876
        },
        {
            name:'Colima',
            abb:'COL',
            idh:0.834
        },
        {
            name:'Chiapas',
            abb:'CHI',
            idh:0.700
        },
        {
            name:'Chihuahua',
            abb:'CHH',
            idh:0.880
        },
        {
            name:'Durango',
            abb:'DUR',
            idh:0.822
        },
        {
            name:'Estado de Mexico',
            abb:'EMX',
            idh:0.820
        },
        {
            name:'Guanajuato',
            abb:'GUA',
            idh:0.789
        },
        {
            name:'Guerrero',
            abb:'GRO',
            idh:0.727
        },
        {
            name:'Hidalgo',
            abb:'HID',
            idh:0.772
        },
        {
            name:'Jalisco',
            abb:'JAL',
            idh:0.836
        },
        {
            name:'Michoacan',
            abb:'MIC',
            idh:0.759
        },
        {
            name: 'Morelos',
            abb: 'MOR',
            idh:0.830
        },
        {
            name:'Nayarit',
            abb:'NAY',
            idh:0.771
        },
        {
            name:'Nuevo Leon',
            abb:'NVL',
            idh:0.905
        },
        {
            name:'Oaxaca',
            abb:'OAX',
            idh:0.711
        },
        {
            name:'Puebla',
            abb:'PUE',
            idh:0.779
        },
        {
            name:'Queretaro',
            abb:'QRO',
            idh:0.853
        },
        {
            name:'Quintana Roo',
            abb:'QNR',
            idh:0.875
        },
        {
            name:'San Luis Potosi',
            abb:'SLP',
            idh:0.802
        },
        {
            name:'Sinaloa',
            abb:'SIN',
            idh:0.811
        },
        {
            name:'Sonora',
            abb:'SON',
            idh:0.864
        },
        {
            name:'Tabasco',
            abb:'TAB',
            idh:0.775
        },
        {
            name:'Tamaulipas',
            abb:'TAM',
            idh:0.854
        },
        {
            name:'Tlaxcala',
            abb:'TLX',
            idh:0.773
        },
        {
            name:'Veracruz',
            abb:'VER',
            idh:0.759
        },
        {
            name:'Yucatan',
            abb:'YUC',
            idh:0.802
        },
        {
            name:'Zacatecas',
            abb:'ZAC',
            idh:0.778
        }
    ]
    ,
    idh2000:[
        {
            name:'Aguascalientes',
            abb:'AGU',
            idh:0.850
        },
        {
            name:'Baja California',
            abb:'BCN',
            idh:0.862
        },
        {
            name: 'Baja California Sur',
            abb:'BCS',
            idh:0.855
        },
        {
            name:'Campeche',
            abb:'CAM',
            idh:0.792
        },
        {
            name: 'Ciudad de Mexico',
            abb: 'CMX',
            idh:0.930
        },
        {
            name:'Coahuila',
            abb: 'COA',
            idh:0.863
        },
        {
            name:'Colima',
            abb:'COL',
            idh:0.826
        },
        {
            name:'Chiapas',
            abb:'CHI',
            idh:0.681
        },
        {
            name:'Chihuahua',
            abb:'CHH',
            idh:0.867
        },
        {
            name:'Durango',
            abb:'DUR',
            idh:0.805
        },
        {
            name:'Estado de Mexico',
            abb:'EMX',
            idh:0.806
        },
        {
            name:'Guanajuato',
            abb:'GUA',
            idh:0.771
        },
        {
            name:'Guerrero',
            abb:'GRO',
            idh:0.713
        },
        {
            name:'Hidalgo',
            abb:'HID',
            idh:0.755
        },
        {
            name:'Jalisco',
            abb:'JAL',
            idh:0.826
        },
        {
            name:'Michoacan',
            abb:'MIC',
            idh:0.746
        },
        {
            name: 'Morelos',
            abb: 'MOR',
            idh:0.807
        },
        {
            name:'Nayarit',
            abb:'NAY',
            idh:0.764
        },
        {
            name:'Nuevo Leon',
            abb:'NVL',
            idh:0.893
        },
        {
            name:'Oaxaca',
            abb:'OAX',
            idh:0.689
        },
        {
            name:'Puebla',
            abb:'PUE',
            idh:0.759
        },
        {
            name:'Queretaro',
            abb:'QRO',
            idh:0.835
        },
        {
            name:'Quintana Roo',
            abb:'QNR',
            idh:0.862
        },
        {
            name:'San Luis Potosi',
            abb:'SLP',
            idh:0.781
        },
        {
            name:'Sinaloa',
            abb:'SIN',
            idh:0.796
        },
        {
            name:'Sonora',
            abb:'SON',
            idh:0.853
        },
        {
            name:'Tabasco',
            abb:'TAB',
            idh:0.762
        },
        {
            name:'Tamaulipas',
            abb:'TAM',
            idh:0.838
        },
        {
            name:'Tlaxcala',
            abb:'TLX',
            idh:0.758
        },
        {
            name:'Veracruz',
            abb:'VER',
            idh:0.743
        },
        {
            name:'Yucatan',
            abb:'YUC',
            idh:0.787
        },
        {
            name:'Zacatecas',
            abb:'ZAC',
            idh:0.753
        }
    ]
    ,
    idh1995:[
        {
            name:'Aguascalientes',
            abb:'AGU',
            idh:0.813 
        },
        {
            name:'Baja California',
            abb:'BCN',
            idh:0.835
        },
        {
            name: 'Baja California Sur',
            abb:'BCS',
            idh:0.839
        },
        {
            name:'Campeche',
            abb:'CAM',
            idh:0.775
        },
        {
            name: 'Ciudad de Mexico',
            abb: 'CMX',
            idh:0.904
        },
        {
            name:'Coahuila',
            abb: 'COA',
            idh:0.835
        },
        {
            name:'Colima',
            abb:'COL',
            idh:0.803
        },
        {
            name:'Chiapas',
            abb:'CHI',
            idh:0.658
        },
        {
            name:'Chihuahua',
            abb:'CHH',
            idh:0.832
        },
        {
            name:'Durango',
            abb:'DUR',
            idh:0.781
        },
        {
            name:'Estado de Mexico',
            abb:'EMX',
            idh:0.775
        },
        {
            name:'Guanajuato',
            abb:'GUA',
            idh:0.812
        },
        {
            name:'Guerrero',
            abb:'GRO',
            idh:0.693
        },
        {
            name:'Hidalgo',
            abb:'HID',
            idh:0.716
        },
        {
            name:'Jalisco',
            abb:'JAL',
            idh:0.795
        },
        {
            name:'Michoacan',
            abb:'MIC',
            idh:0.714
        },
        {
            name: 'Morelos',
            abb: 'MOR',
            idh:0.779
        },
        {
            name:'Nayarit',
            abb:'NAY',
            idh:0.739
        },
        {
            name:'Nuevo Leon',
            abb:'NVL',
            idh:0.864
        },
        {
            name:'Oaxaca',
            abb:'OAX',
            idh:0.666
        },
        {
            name:'Puebla',
            abb:'PUE',
            idh:0.719
        },
        {
            name:'Queretaro',
            abb:'QRO',
            idh:0.795
        },
        {
            name:'Quintana Roo',
            abb:'QNR',
            idh:0.845
        },
        {
            name:'San Luis Potosi',
            abb:'SLP',
            idh:0.743
        },
        {
            name:'Sinaloa',
            abb:'SIN',
            idh:0.780
        },
        {
            name:'Sonora',
            abb:'SON',
            idh:0.827
        },
        {
            name:'Tabasco',
            abb:'TAB',
            idh:0.746
        },
        {
            name:'Tamaulipas',
            abb:'TAM',
            idh:0.808
        },
        {
            name:'Tlaxcala',
            abb:'TLX',
            idh:0.724
        },
        {
            name:'Veracruz',
            abb:'VER',
            idh:0.723
        },
        {
            name:'Yucatan',
            abb:'YUC',
            idh:0.750
        },
        {
            name:'Zacatecas',
            abb:'ZAC',
            idh:0.729
        }
    ]
    ,
    idh1990:[
        {
            name:'Aguascalientes',
            abb:'AGU',
            idh:0.804 
        },
        {
            name:'Baja California',
            abb:'BCN',
            idh:0.850
        },
        {
            name: 'Baja California Sur',
            abb:'BCS',
            idh:0.838
        },
        {
            name:'Campeche',
            abb:'CAM',
            idh:0.785
        },
        {
            name: 'Ciudad de Mexico',
            abb: 'CMX',
            idh:0.911
        },
        {
            name:'Coahuila',
            abb: 'COA',
            idh:0.816
        },
        {
            name:'Colima',
            abb:'COL',
            idh:0.793
        },
        {
            name:'Chiapas',
            abb:'CHI',
            idh:0.647
        },
        {
            name:'Chihuahua',
            abb:'CHH',
            idh:0.838
        },
        {
            name:'Durango',
            abb:'DUR',
            idh:0.773
        },
        {
            name:'Estado de Mexico',
            abb:'EMX',
            idh:0.791
        },
        {
            name:'Guanajuato',
            abb:'GUA',
            idh:0.731
        },
        {
            name:'Guerrero',
            abb:'GRO',
            idh:0.683
        },
        {
            name:'Hidalgo',
            abb:'HID',
            idh:0.725
        },
        {
            name:'Jalisco',
            abb:'JAL',
            idh:0.801
        },
        {
            name:'Michoacan',
            abb:'MIC',
            idh:0.704
        },
        {
            name: 'Morelos',
            abb: 'MOR',
            idh:0.779
        },
        {
            name:'Nayarit',
            abb:'NAY',
            idh:0.741
        },
        {
            name:'Nuevo Leon',
            abb:'NVL',
            idh:0.867
        },
        {
            name:'Oaxaca',
            abb:'OAX',
            idh:0.658
        },
        {
            name:'Puebla',
            abb:'PUE',
            idh:0.719
        },
        {
            name:'Queretaro',
            abb:'QRO',
            idh:0.719
        },
        {
            name:'Quintana Roo',
            abb:'QNR',
            idh:0.780
        },
        {
            name:'San Luis Potosi',
            abb:'SLP',
            idh:0.746
        },
        {
            name:'Sinaloa',
            abb:'SIN',
            idh:0.774
        },
        {
            name:'Sonora',
            abb:'SON',
            idh:0.828
        },
        {
            name:'Tabasco',
            abb:'TAB',
            idh:0.754
        },
        {
            name:'Tamaulipas',
            abb:'TAM',
            idh:0.809
        },
        {
            name:'Tlaxcala',
            abb:'TLX',
            idh:0.728
        },
        {
            name:'Veracruz',
            abb:'VER',
            idh:0.722
        },
        {
            name:'Yucatan',
            abb:'YUC',
            idh:0.744
        },
        {
            name:'Zacatecas',
            abb:'ZAC',
            idh:0.730
        }
    ]
    ,
    idh1980:[
        {
            name:'Aguascalientes',
            abb:'AGU',
            idh:0.737
        },
        {
            name:'Baja California',
            abb:'BCN',
            idh:0.796
        },
        {
            name: 'Baja California Sur',
            abb:'BCS',
            idh:0.787
        },
        {
            name:'Campeche',
            abb:'CAM',
            idh:0.647
        },
        {
            name: 'Ciudad de Mexico',
            abb: 'CMX',
            idh:0.828
        },
        {
            name:'Coahuila',
            abb: 'COA',
            idh:0.770
        },
        {
            name:'Colima',
            abb:'COL',
            idh:0.719
        },
        {
            name:'Chiapas',
            abb:'CHI',
            idh:0.598
        },
        {
            name:'Chihuahua',
            abb:'CHH',
            idh:0.777
        },
        {
            name:'Durango',
            abb:'DUR',
            idh:0.722
        },
        {
            name:'Estado de Mexico',
            abb:'EMX',
            idh:0.743
        },
        {
            name:'Guanajuato',
            abb:'GUA',
            idh:0.665
        },
        {
            name:'Guerrero',
            abb:'GRO',
            idh:0.607
        },
        {
            name:'Hidalgo',
            abb:'HID',
            idh:0.649
        },
        {
            name:'Jalisco',
            abb:'JAL',
            idh:0.742
        },
        {
            name:'Michoacan',
            abb:'MIC',
            idh:0.648
        },
        {
            name: 'Morelos',
            abb: 'MOR',
            idh:0.699
        },
        {
            name:'Nayarit',
            abb:'NAY',
            idh:0.689
        },
        {
            name:'Nuevo Leon',
            abb:'NVL',
            idh:0.800
        },
        {
            name:'Oaxaca',
            abb:'OAX',
            idh:0.576
        },
        {
            name:'Puebla',
            abb:'PUE',
            idh:0.658
        },
        {
            name:'Queretaro',
            abb:'QRO',
            idh:0.693
        },
        {
            name:'Quintana Roo',
            abb:'QNR',
            idh:0.738
        },
        {
            name:'San Luis Potosi',
            abb:'SLP',
            idh:0.661
        },
        {
            name:'Sinaloa',
            abb:'SIN',
            idh:0.713
        },
        {
            name:'Sonora',
            abb:'SON',
            idh:0.759
        },
        {
            name:'Tabasco',
            abb:'TAB',
            idh:0.677
        },
        {
            name:'Tamaulipas',
            abb:'TAM',
            idh:0.759
        },
        {
            name:'Tlaxcala',
            abb:'TLX',
            idh:0.660
        },
        {
            name:'Veracruz',
            abb:'VER',
            idh:0.667
        },
        {
            name:'Yucatan',
            abb:'YUC',
            idh:0.691
        },
        {
            name:'Zacatecas',
            abb:'ZAC',
            idh:0.663
        }
    ]
    ,
}

export default IDH